apiVersion: v1
kind: ConfigMap
metadata:
  name: baetyl-cloud-config
  namespace: default
data:
  client_ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIICYjCCAgigAwIBAgIDAYaiMAoGCCqGSM49BAMCMIGlMQswCQYDVQQGEwJDTjEQ
    MA4GA1UECBMHQmVpamluZzEZMBcGA1UEBxMQSGFpZGlhbiBEaXN0cmljdDEVMBMG
    A1UECRMMQmFpZHUgQ2FtcHVzMQ8wDQYDVQQREwYxMDAwOTMxHjAcBgNVBAoTFUxp
    bnV4IEZvdW5kYXRpb24gRWRnZTEPMA0GA1UECxMGQkFFVFlMMRAwDgYDVQQDEwdy
    b290LmNhMCAXDTIwMDMyNzA5NTc1NFoYDzIwNTAwMzI3MDk1NzU0WjCBpTELMAkG
    A1UEBhMCQ04xEDAOBgNVBAgTB0JlaWppbmcxGTAXBgNVBAcTEEhhaWRpYW4gRGlz
    dHJpY3QxFTATBgNVBAkTDEJhaWR1IENhbXB1czEPMA0GA1UEERMGMTAwMDkzMR4w
    HAYDVQQKExVMaW51eCBGb3VuZGF0aW9uIEVkZ2UxDzANBgNVBAsTBkJBRVRZTDEQ
    MA4GA1UEAxMHcm9vdC5jYTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABOuYHJY0
    83AeXWAR45lbRRzICdJzoyl0zOFIK6WW7XuJWD/HhYxCedYPaumgwVI7RRsNb+61
    VpS95aFMCMDW4yqjIzAhMA4GA1UdDwEB/wQEAwIBhjAPBgNVHRMBAf8EBTADAQH/
    MAoGCCqGSM49BAMCA0gAMEUCIGhBsis/RIa4+mzBeDwrICAcYZhjqQRc8pP172gQ
    yVRvAiEAyRzj7kln/xXd1yPW6BE/cavCp6tmwpvADUlaXS5FE9M=
    -----END CERTIFICATE-----
  client_ca.key: |-
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEII0qZCQMJ3QD6FmhD5PExE5qndQNh1tV5fQy7JGpHbCHoAoGCCqGSM49
    AwEHoUQDQgAE65gcljTzcB5dYBHjmVtFHMgJ0nOjKXTM4UgrpZbte4lYP8eFjEJ5
    1g9q6aDBUjtFGw1v7rVWlL3loUwIwNbjKg==
    -----END EC PRIVATE KEY-----
  server.crt: |-
    -----BEGIN CERTIFICATE-----
    MIICsDCCAlegAwIBAgIDAYahMAoGCCqGSM49BAMCMIGsMQswCQYDVQQGEwJDTjEQ
    MA4GA1UECBMHQmVpamluZzEZMBcGA1UEBxMQSGFpZGlhbiBEaXN0cmljdDEVMBMG
    A1UECRMMQmFpZHUgQ2FtcHVzMQ8wDQYDVQQREwYxMDAwOTMxHjAcBgNVBAoTFUxp
    bnV4IEZvdW5kYXRpb24gRWRnZTEPMA0GA1UECxMGQkFFVFlMMRcwFQYDVQQDEw5j
    bGllbnQucm9vdC5jYTAgFw0yMDAzMjcwOTU1MzVaGA8yMDUwMDMyNzA5NTUzNVow
    gaoxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRkwFwYDVQQHExBIYWlk
    aWFuIERpc3RyaWN0MRUwEwYDVQQJEwxCYWlkdSBDYW1wdXMxDzANBgNVBBETBjEw
    MDA5MzEeMBwGA1UEChMVTGludXggRm91bmRhdGlvbiBFZGdlMQ8wDQYDVQQLEwZC
    QUVUWUwxFTATBgNVBAMTDGNsb3VkLnNlcnZlcjBZMBMGByqGSM49AgEGCCqGSM49
    AwEHA0IABKx0tiiKiXS1VcTTK+caqmvYeRVSvyJr3gpZ+oUhCUAmMOTR1Fm2uIfm
    P/fErAklhcZY1H8+J87EM5sG11qWcnqjZjBkMA4GA1UdDwEB/wQEAwIFoDATBgNV
    HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMC8GA1UdEQQoMCaCJGd6aHh5
    LXkzMi1zYW5kYm94MDMxLmd6aHh5LmJhaWR1LmNvbTAKBggqhkjOPQQDAgNHADBE
    AiAm5dm4oKY5WFN2eD4xBJIWG/I4IRBH7yVxH3U5SkxaGAIgJIr3gyQEZxySIwPQ
    fm56/vWqdMIBTOmtv8q+ixF3Ves=
    -----END CERTIFICATE-----
  server.key: |-
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIG/B4w19XHDyb78DLNKPD+sacQvIIjvoIihW6voRjNGQoAoGCCqGSM49
    AwEHoUQDQgAErHS2KIqJdLVVxNMr5xqqa9h5FVK/ImveCln6hSEJQCYw5NHUWba4
    h+Y/98SsCSWFxljUfz4nzsQzmwbXWpZyeg==
    -----END EC PRIVATE KEY-----
  server_ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIICcDCCAhagAwIBAgIDAYagMAoGCCqGSM49BAMCMIGsMQswCQYDVQQGEwJDTjEQ
    MA4GA1UECBMHQmVpamluZzEZMBcGA1UEBxMQSGFpZGlhbiBEaXN0cmljdDEVMBMG
    A1UECRMMQmFpZHUgQ2FtcHVzMQ8wDQYDVQQREwYxMDAwOTMxHjAcBgNVBAoTFUxp
    bnV4IEZvdW5kYXRpb24gRWRnZTEPMA0GA1UECxMGQkFFVFlMMRcwFQYDVQQDEw5j
    bGllbnQucm9vdC5jYTAgFw0yMDAzMjcwOTU1MzVaGA8yMDUwMDMyNzA5NTUzNVow
    gawxCzAJBgNVBAYTAkNOMRAwDgYDVQQIEwdCZWlqaW5nMRkwFwYDVQQHExBIYWlk
    aWFuIERpc3RyaWN0MRUwEwYDVQQJEwxCYWlkdSBDYW1wdXMxDzANBgNVBBETBjEw
    MDA5MzEeMBwGA1UEChMVTGludXggRm91bmRhdGlvbiBFZGdlMQ8wDQYDVQQLEwZC
    QUVUWUwxFzAVBgNVBAMTDmNsaWVudC5yb290LmNhMFkwEwYHKoZIzj0CAQYIKoZI
    zj0DAQcDQgAE6FKiZEEPgkBbQwqd8vHX7+NPEa3j33WbTz0/xMcoAZTbg9yMZR/9
    BfNjArw3rUHc4K9aMNnlFYXu1RCgdLiIxqMjMCEwDgYDVR0PAQH/BAQDAgGGMA8G
    A1UdEwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSAAwRQIhAKV27nEL++GfZoA8WGBw
    q2MjYpZ2G6tvqQIa9oBI7z/dAiA3z47euYsWN2/rPjRoHTDAa9aZ6bBOXr8t0fKX
    sgQJMw==
    -----END CERTIFICATE-----
  service.yml: |-
    nodeServer:
      port: ":9005"
      ca: "/etc/baetyl/client_ca.crt"
      cert: "/etc/baetyl/server.crt"
      key: "/etc/baetyl/server.key"

    activeServer:
      port: ":9003"
      ca: "/etc/baetyl/server_ca.crt"
      cert: "/etc/baetyl/server.crt"
      key: "/etc/baetyl/server.key"

    adminServer:
      port: ":9004"

    database:
      type: "mysql"
      url: "root:12345678@(host.docker.internal:3306)/baetyl_cloud?charset=utf8&parseTime=true"

    kubernetes:
      inCluster: true

    plugin:
      modelStorage: "kubernetes"
      databaseStorage: "database"

    defaultpki:
      rootCAFile: "/etc/baetyl/client_ca.crt"
      rootCAKeyFile: "/etc/baetyl/client_ca.key"
      rootCertId: "98ec3bc552f0478298aa1c6702a95427"
      persistent:
        kind: "database"
        database:
          type: "mysql"
          url: "root:12345678@(host.docker.internal:3306)/baetyl_cloud?charset=utf8&parseTime=true"

    defaultauth:
      namespace: "baetyl-cloud"
      keyFile: "/etc/baetyl/token.key"
  token.key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA41Ux2wPALzq5agrwhNOr0B+BYePAf5CrVPXtfFKmQDdOqBkB
    jM5M61cXyWkcET3d/nKyewvNvWjKjXbaWxxaHAbQsen/5vcte9drW5dVvAquYi45
    nQDI2gM00u0FAARydqMzYRFZZir7a3d/tsHiH9HWjkOBkXiBpvDWHXjIRBfCRdgX
    3rSwnHDh1Tc0se7rX+0lo8mw7jFCUEH1l9vF/jFE3BGUHK7UHEPg2gDP7w2L8VOF
    vTk2rQRGhy2jE3P4xF5x64i8KzOpJw8rbxBezL/yYNcpjuFkkrCpWVLHEgarHPCx
    HLB8HkUGAnlM9Apx613icvtRf+sqW1J+F2qfSQIDAQABAoIBAFNrouTcpnxuTzXD
    l+kWB5lSxlaWjcAB5W1C5YfWiF1OLlXu/yudVIqTpg3pvTvyePDzQ911QmU7/AAX
    Wh9O8x4PvitbU+V8VLt6HFI64WIkhUNP9SJQ9GNUA+FWypvsBdjVIHiBNk4Qfbw8
    2KfG0+SbSuFfkj9Aeks5W0jrVontgPSumKy8oI0Y4BsvqjJmwK+c5EHqQ0pZ5x4D
    pluqyArQrAbHLMpfpVtaQXiAFdKnLwVTjEl+kZGFgkoJeoNbHGNQabvvH6fjzvPt
    8DM44Bs4IvUppIHI6sd42XhcyfYXG/HjynUYtND8I0wWIqabOJJHxE71fQ2i8BfU
    Y4qxe0UCgYEA7vUzrbr/a8q0iVrp0rG+98E6c3tuPBNB9cYX16dX20PBhxDznsFJ
    6uWdef4x87texQDKYeDScsR9nMiTX7AQDQqMCLHbp65oZGZlXmHJ9LwC7Ppwo3Fc
    kt8JGheS+6i6/+SqKAVPyoKMdC5pHQR/APsYmmodq8hLPEQZZfYOuyMCgYEA84u/
    aAc6y7m3WdmsNCxwV4eEkqParrmlYCYHtWRqdRL5M3qg6AYSBZJUCzgPz+YtSPON
    hO5/1Vq5WzNOMwdbtKT7M7AwCdI0OrInyEq3gKnfsJP3Dbzj54JUcc+JdZqR+m3E
    5deBoVBuCp0x0/oVpHcgsEBe4yiUBXAB3UjEKKMCgYEAxdRImY8UATiLaJ/UrvMq
    x9C4RH0ukRvcYs5CVO6dBNE+ekSlfIxHVuoMCsBQuJkp5201H/1SHWPhHpjLsc+A
    KlvN/TDKSjNRB7XiPFY3LZ8tyOW5tQaX/pwZ2/kiXaieUFYOLR3gpiaYg2Mc8MIV
    J0m6X7R0phAngVhbspcYMQMCgYAuRv6u4LjOX1K0swTiwRLzvt91EceK7eG7vF44
    nIUSC/HoU0Ph8s1X2682loeCpKU0OHtKqBsISn3wE3angZ1uXO8Sqkbmhte/03x1
    taTawOytW+BU7vCLXBt5qMrg2uckI9mHJwUNxv+x6p6+PcYBA1Xlx8V/+oTt55Oj
    HaGQawKBgAFjOYIs9tZaTqeHFQkw1zs2Da4e54mMp153XGFcby+2N9XQfs8BQitG
    CjpiLI/QVvYXOShRZK/cnMJBmqBhec8534D5GxwTeg/xUNlTq+G/9goLMtWKlBZp
    rjBUmKcoSNjVQ8UgIBiSXG0XlCNv+rC23eE5gg0OLLBsPIEOuuSf
    -----END RSA PRIVATE KEY-----
