# Get content by command "kubectl config view --raw", than change the follow example.
# Example:
apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: "https://kubernetes.docker.internal:6443"
    name: Default
contexts:
  - context:
      cluster: Default
      user: Default
    name: Default
current-context: Default
kind: Config
preferences: { }
users:
  - name: Default
    user:
      token: kubectl-shell-user-k8z88:xxxxxxxxxxxxxxxx